### ISSUE TITLE
cette semaine = +7j

### ISSUE THREAD

**Issue by nicomq** [scdantilles/scdcalendar#1]
Dans scdcalendar.module pour affichage une semaine on devrait avoir non pas cette semaine - avec par ex 3j slt si tu cliques un mercredi - mais plutot +8j

![image](https://cloud.githubusercontent.com/assets/10815686/12627211/03e37494-c513-11e5-9481-38c92673ffb3.png)

**Comment by kivutar** [comment]
Fait.
