### ISSUE TITLE
cette année: ne se met pas à jour?

### ISSUE THREAD

**Issue by nicomq** [scdantilles/scdcalendar#3]
http://angole.martinique.univ-ag.fr/node/6/thisyearlib par ex.
Si tu regardes la mm bibliothèque pour cette semaine, j'ai mis à jour hier et elle est ouverte dans les jours et semaines à venir. Mais au niveau de l'affichage année, elle semble conserver des jours d'ouvertures correspondant à un ancien état.

**Comment by kivutar** [comment]
Il y a un 2015 hardcodé dans le module. Je vais régler ça...

**Comment by kivutar** [comment]
Réglé
